version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_RETENTION_CHECK_INTERVAL_MS: 20000
      KAFKA_OFFSETS_RETENTION_MINUTES: 2
      KAFKA_OFFSETS_TOPIC_SEGMENT_BYTES: 2048
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
